/**
 * Class source backed by the bundled JDK core index
 * (resources/jdk-core-index.json, generated by scripts/GenerateJdkIndex.java).
 * Everything is pre-parsed: loading a class is a map lookup.
 */

import * as fs from "fs/promises";
import { ClassSource } from "./ClassIndexService";
import { JavaClassInfo } from "./model";

interface JdkCoreIndex {
    classes: JavaClassInfo[];
}

export class JdkClassSource implements ClassSource {

    private constructor(private readonly classes: Map<string, JavaClassInfo>) { }

    /** Loads the bundled index; throws if the file is missing or malformed */
    public static async load(indexPath: string): Promise<JdkClassSource> {
        const raw = await fs.readFile(indexPath, "utf8");
        const index = JSON.parse(raw) as JdkCoreIndex;
        const classes = new Map<string, JavaClassInfo>();
        for (const info of index.classes) {
            classes.set(info.fqcn, info);
        }
        return new JdkClassSource(classes);
    }

    public listClassNames(): ReadonlyArray<string> {
        return [...this.classes.keys()];
    }

    public loadClass(fqcn: string): Promise<JavaClassInfo | undefined> {
        return Promise.resolve(this.classes.get(fqcn));
    }

    public dispose(): void {
        // Nothing to release
    }
}
